// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dynamic-location-group.proto
// </auto-generated>
// Original file comments:
// Dynamic Location Group APIs
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DistributedMatchEngine {
  public static partial class DynamicLocGroupApi
  {
    static readonly string __ServiceName = "distributed_match_engine.DynamicLocGroupApi";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::DistributedMatchEngine.DlgMessage> __Marshaller_distributed_match_engine_DlgMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DistributedMatchEngine.DlgMessage.Parser));
    static readonly grpc::Marshaller<global::DistributedMatchEngine.DlgReply> __Marshaller_distributed_match_engine_DlgReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DistributedMatchEngine.DlgReply.Parser));

    static readonly grpc::Method<global::DistributedMatchEngine.DlgMessage, global::DistributedMatchEngine.DlgReply> __Method_SendToGroup = new grpc::Method<global::DistributedMatchEngine.DlgMessage, global::DistributedMatchEngine.DlgReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendToGroup",
        __Marshaller_distributed_match_engine_DlgMessage,
        __Marshaller_distributed_match_engine_DlgReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DistributedMatchEngine.DynamicLocationGroupReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for DynamicLocGroupApi</summary>
    public partial class DynamicLocGroupApiClient : grpc::ClientBase<DynamicLocGroupApiClient>
    {
      /// <summary>Creates a new client for DynamicLocGroupApi</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DynamicLocGroupApiClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DynamicLocGroupApi that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DynamicLocGroupApiClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DynamicLocGroupApiClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DynamicLocGroupApiClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::DistributedMatchEngine.DlgReply SendToGroup(global::DistributedMatchEngine.DlgMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendToGroup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DistributedMatchEngine.DlgReply SendToGroup(global::DistributedMatchEngine.DlgMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendToGroup, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DistributedMatchEngine.DlgReply> SendToGroupAsync(global::DistributedMatchEngine.DlgMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendToGroupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DistributedMatchEngine.DlgReply> SendToGroupAsync(global::DistributedMatchEngine.DlgMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendToGroup, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DynamicLocGroupApiClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DynamicLocGroupApiClient(configuration);
      }
    }

  }
}
#endregion
