// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: edgeprotogen.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Edgeprotogen {

  /// <summary>Holder for reflection information generated from edgeprotogen.proto</summary>
  public static partial class EdgeprotogenReflection {

    #region Descriptor
    /// <summary>File descriptor for edgeprotogen.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EdgeprotogenReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJlZGdlcHJvdG9nZW4ucHJvdG8SDGVkZ2Vwcm90b2dlbhogZ29vZ2xlL3By",
            "b3RvYnVmL2Rlc2NyaXB0b3IucHJvdG86OQoMZW51bV9iYWNrZW5kEiEuZ29v",
            "Z2xlLnByb3RvYnVmLkVudW1WYWx1ZU9wdGlvbnMY4o4DIAEoCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
