
   
name: MobiledgeX C# Docs Update

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2
      - name: Update Docs
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:  
          working-directory: 'rest/'
          doxyfile-path: './Doxygen/Doxyfile'
      - name: Move generated docs to docs directory
        run: |
           sudo rm -rf docs/*
           sudo mv rest/html/ docs/
        shell: bash
      - name: Commit Doxygen Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Docs Automated Updates
            branch: automated-docs 
            push_options: '--force'