name: MobiledgeX C# Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2
      - name: Download Doxygen
        run: |
           apt-get update
           apt install build-essential xz-utils curl cmake flex bison git
           git clone https://github.com/doxygen/doxygen.git
           cd doxygen
           mkdir build
           cd build
           cmake -G "Unix Makefiles" ..
           make
           make install
        shell: bash
      - name: Update docs
        run: |
           make generate-doxygen
        shell: bash
        working-directory: ./rest/

      - name: Commit Doxygen Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Docs Automated Updates
            branch: automated-docs