name: MobiledgeX C# Docs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2
      - name: Update Docs
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:  
          working-directory: 'rest/'
          doxyfile-path: './Doxygen/Doxyfile'
      - name: Commit Doxygen Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Docs Automated Updates
            branch: automated-docs